blank_issues_enabled: false
contact_links:
  - name: ❓ Ask a question
    url: https://github.com/toodofun/gvm/discussions/new?category=q-a
    about:  Ask and discuss questions with other gvm community members