name: lint and Test

on: [push, pull_request]

jobs:
  lint_and_test:
    name: Lint and Test - ${{ matrix.go-version }}
    strategy:
      matrix:
        go-version: [1.24.x, 1.23.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    environment:
      name: gvm-ci
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          make tools

      - name: Check copyright
        run: |
          make verify-copyright

      - name: Check syntax and styling of go sources
        run: |
          make lint
        if: |
          matrix.go-version == '1.24.x'

      - name: Run unit test and get test coverage
        run: |
          make cover

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: toodofun/gvm
          files: _output/coverage.out
        if: |
          matrix.go-version == '1.23.x'